<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="A"
    nsURI="A" nsPrefix="A">
  <eClassifiers xsi:type="ecore:EDataType" name="D1" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="C1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="d1" eType="#//D1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c1" eType="#//D1"/>
  </eClassifiers>
</ecore:EPackage>
